const header=document.querySelector(".site-header"),progressBar=document.querySelector(".progress span"),menuToggle=document.querySelector(".menu-toggle"),navigation=document.querySelector(".main-nav"),navigationLinks=[...document.querySelectorAll(".main-nav a")],themeToggle=document.querySelector(".theme-toggle"),languageSwitcher=document.querySelector(".language-switcher"),languageToggle=languageSwitcher?.querySelector('a[aria-current="page"]'),languageOptions=languageSwitcher?[...languageSwitcher.querySelectorAll('a:not([aria-current="page"])')]:[],year=document.getElementById("year"),themeKey="site-theme",reduceMotion=window.matchMedia?.("(prefers-reduced-motion: reduce)").matches,isEnglish=document.documentElement.lang.toLowerCase().startsWith("en");

const uiText=isEnglish?{openMenu:"Open menu",closeMenu:"Close menu",enableLightTheme:"Enable light theme",enableDarkTheme:"Enable dark theme",lightTheme:"Light theme",darkTheme:"Dark theme"}:{openMenu:"Открыть меню",closeMenu:"Закрыть меню",enableLightTheme:"Включить светлую тему",enableDarkTheme:"Включить тёмную тему",lightTheme:"Светлая тема",darkTheme:"Тёмная тема"};

function applyTheme(theme,save=false){const light=theme==="light";document.documentElement.classList.toggle("theme-light",light);document.documentElement.style.colorScheme=light?"light":"dark";if(themeToggle){themeToggle.setAttribute("aria-pressed",String(light));themeToggle.setAttribute("aria-label",light?uiText.enableDarkTheme:uiText.enableLightTheme);themeToggle.title=light?uiText.darkTheme:uiText.lightTheme}if(save){try{localStorage.setItem(themeKey,theme)}catch{}}}
try{applyTheme(localStorage.getItem(themeKey)||"dark")}catch{applyTheme("dark")}
themeToggle?.addEventListener("click",()=>applyTheme(document.documentElement.classList.contains("theme-light")?"dark":"light",true));

function closeMenu(){if(!navigation||!menuToggle)return;navigation.classList.remove("open");menuToggle.classList.remove("open");menuToggle.setAttribute("aria-expanded","false");menuToggle.setAttribute("aria-label",uiText.openMenu)}
menuToggle?.addEventListener("click",()=>{if(!navigation)return;const open=navigation.classList.toggle("open");menuToggle.classList.toggle("open",open);menuToggle.setAttribute("aria-expanded",String(open));menuToggle.setAttribute("aria-label",open?uiText.closeMenu:uiText.openMenu)});
navigationLinks.forEach(link=>link.addEventListener("click",closeMenu));

function setLanguageMenu(open){if(!languageSwitcher||!languageToggle)return;languageSwitcher.classList.toggle("is-open",open);languageToggle.setAttribute("aria-expanded",String(open));languageOptions.forEach(option=>option.tabIndex=open?0:-1)}
function closeLanguageMenu(focus=false){if(!languageSwitcher?.classList.contains("is-open"))return;setLanguageMenu(false);if(focus)languageToggle?.focus()}
if(languageSwitcher&&languageToggle){languageSwitcher.classList.add("is-ready");languageToggle.setAttribute("role","button");languageToggle.setAttribute("aria-haspopup","true");languageToggle.setAttribute("aria-expanded","false");languageOptions.forEach(option=>option.tabIndex=-1);languageToggle.addEventListener("click",event=>{event.preventDefault();setLanguageMenu(!languageSwitcher.classList.contains("is-open"))});languageToggle.addEventListener("keydown",event=>{if(event.key!=="ArrowDown")return;event.preventDefault();setLanguageMenu(true);languageOptions[0]?.focus()})}

document.addEventListener("keydown",event=>{if(event.key!=="Escape")return;closeMenu();closeLanguageMenu(true)});
document.addEventListener("click",event=>{if(navigation?.classList.contains("open")&&!navigation.contains(event.target)&&!menuToggle?.contains(event.target))closeMenu();if(languageSwitcher?.classList.contains("is-open")&&!languageSwitcher.contains(event.target))closeLanguageMenu()});

let scrollFrame=0;function updateScrollState(){scrollFrame=0;if(header)header.classList.toggle("scrolled",window.scrollY>10);if(progressBar){const max=document.documentElement.scrollHeight-window.innerHeight;progressBar.style.width=`${max>0?window.scrollY/max*100:0}%`}}function requestScrollUpdate(){if(!scrollFrame)scrollFrame=window.requestAnimationFrame(updateScrollState)}updateScrollState();window.addEventListener("scroll",requestScrollUpdate,{passive:true});window.addEventListener("resize",requestScrollUpdate,{passive:true});

const sections=[...document.querySelectorAll("main section[id]")];if("IntersectionObserver"in window&&sections.length&&navigationLinks.length){const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(!visible)return;navigationLinks.forEach(link=>{const active=link.getAttribute("href")===`#${visible.target.id}`;link.classList.toggle("active",active);if(active)link.setAttribute("aria-current","page");else link.removeAttribute("aria-current")})},{rootMargin:"-35% 0px -55% 0px",threshold:0});sections.forEach(section=>observer.observe(section))}

const revealItems=[...document.querySelectorAll(".reveal")];if(!reduceMotion&&"IntersectionObserver"in window){revealItems.forEach(item=>item.classList.add("will-reveal"));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add("in");observer.unobserve(entry.target)}),{threshold:.12});revealItems.forEach(item=>observer.observe(item))}year?.append(String(new Date().getFullYear()));
